//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Property
{
    public int Id { get; set; }
    public Nullable<double> rent { get; set; }
    public Nullable<int> rooms { get; set; }
    public string address { get; set; }
    public string type { get; set; }
    public string id_owner { get; set; }
    public string location { get; set; }
}
