<?xml version="1.0" encoding="utf-8"?><Database Name="iFinanciera" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=iFinanciera;User ID=todos;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="iFinancieraConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CreditCard" Member="CreditCard">
    <Type Name="CreditCard">
      <Column Name="IdCreditCard" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="number" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="holder" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payments" Member="Payments">
    <Type Name="Payments">
      <Column Name="IdPayments" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdCreditCard" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>